config/routes.rb
Rails.application.routes.draw do
  resources :educationals
  resources :degrees
  resources :universities
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  root :to => "main#home_page"

  devise_for :users
  resources :stipends
  resources :sponsords
  resources :categories
  resources :students do 
    collection do
      resources :registration
    end
  end

  # => Student Movement
  get '/registered_students', to: 'student_movement#registered_students', as: 'registered_students'
  get '/update_status/:id', to: 'student_movement#update_status', as: 'update_status'
  get '/students_stipend', to: 'student_movement#students_stipend', as: 'students_stipend'
  get '/clear_pervious/:id', to: 'give_stipend#clear_pervious', as: 'clear_pervious'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home_page]

  def home_page
    @todays_notices = Notice.todays_notices
  end
end

app/views/main/_dash_board.html.erb
<%= render 'notices' %>
<div class="col-md-12 row">
  <div class="row col-md-6">
    <div class="col-md-3 p-2" style="max-width: 200px">
      <%= link_to "Students", students_path, class: "btn btn-light d-block m-2" %>
    </div>
    <div class="col-md-3 p-2" style="max-width: 200px">
      <%= link_to "Stipends", stipends_path, class: "btn btn-light d-block m-2" %>
    </div>
    <div class="col-md-3 p-2" style="max-width: 200px">
      <%= link_to "Sponsords", sponsords_path, class: "btn btn-light d-block m-2" %>
    </div>
    <div class="col-md-3 p-2" style="max-width: 200px">
      <%= link_to "Categories", categories_path, class: "btn btn-light d-block m-2" %>  
    </div>
  </div>
  <div class="container row">
    <div class="p-2 col-md-3" style="max-width: 200px">
      <%= link_to "Students for Approval", registered_students_path, class: "btn btn-light d-block m-2" %>
    </div>
    <div class="p-2 col-md-3" style="max-width: 200px">
      <%= link_to "Pending Students", students_stipend_path, class: "btn btn-light d-block m-2" %>
    </div>
  </div>
</div>

app/views/main/_notices.html.erb
<div style="position: relative;">
  <div  style="position: absolute; right: 0px;">
    <% @todays_notices.each do |notice| %>
      <div class="alert alert-<%= notice.alert %> alert-dismissible fade show m-3" role="alert">
        <span class="me-3">
          <strong><%= notice.name %>: </strong> <%= notice.message %>
        </span>
        <button type="button" class="close btn btn-dark close-by-js" data-dismiss="alert" aria-label="Close" style="position: absolute; right: 10px; top: 10px;">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/main/_student_cards.html.erb
<div class="container m-5 d-flex">
  <% (0..2).each do |student| %>
    <div class="card m-2" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Student Name</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.Some quick example text to build on the card title and make up the bulk of the card's content.Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Student Record</a>
      </div>
    </div>
  <% end %>
</div>

app/views/main/_without_signup.html.erb
<div class="row h-100 design-display">
  <div class="col-md-8">
      <%= render "student_cards" %>
  </div>
  <div class="col-md-4 mt-5 container w-25">
    <%= form_for(:user, :url => session_path(:user), :html => {:class => "row g-3"}) do |f| %>

      <div class="col-md-12 text-center text-white">
        <h3>
          Log In
        </h3>
      </div>
      <div class="col-md-12">
        <%= f.text_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>

      <div class="col-md-12">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
      </div>

      <div class="col-md-12">
        <%= f.label :remember_me, class: "text-white" %>
        <%= f.check_box :remember_me %>
      </div>
      <div class="col-md-6">
      <%= f.submit 'Sign in', class: "btn btn-primary w-50 m-2" %>
      </div>
      <div class="col-md-6">
      <%= link_to "Forgot your password?", new_password_path(:user), class: "btn btn-secondary  m-2" %>
      </div>
    <% end %>
    <div class="text-white row mt-5">
      <p class="">Apply for scholarship, <%= link_to "Registered Here", new_registration_path, class: "text-white" %></p>
    </div>
        <%# image_tag "hhs", class: "d-block w-100 h-25" %>
  </div>
</div>

app/views/main/home_page.html.erb
<%= render "shared/header", show_gradient: true %>
<div class="design-display">
<% if signed_in? %>
  <%= render "dash_board" %>
<% else %>
  <%= render "without_signup" %>
<% end %>
</div>
<%= render "shared/footer" %>