config/routes.rb
Rails.application.routes.draw do
  resources :educationals
  resources :degrees
  resources :universities
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  root :to => "main#home_page"

  devise_for :users
  resources :stipends
  resources :sponsords
  resources :categories
  resources :students do 
    collection do
      resources :registration
    end
  end

  # => Student Movement
  get '/registered_students', to: 'student_movement#registered_students', as: 'registered_students'
  get '/update_status/:id', to: 'student_movement#update_status', as: 'update_status'
  get '/students_stipend', to: 'student_movement#students_stipend', as: 'students_stipend'
  get '/clear_pervious/:id', to: 'give_stipend#clear_pervious', as: 'clear_pervious'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/student_movement_controller.rb
class StudentMovementController < ApplicationController
  before_action :set_student, only: %i[update_status]

  def registered_students
    @students = Student.registered.order_by_created.paginate(page: params[:page], per_page: 10)
  end

  def update_status
    respond_to do |format|
      if change_status
        format.html { redirect_to redirect_back_path(params[:redirect_back]), notice: "#{@student.name.capitalize} was successfully #{params[:state]}." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def students_stipend
    @all_students = Student.approved.pending_from(date_from, date_to).order_by_created
    @students = @all_students.paginate(page: params[:page], per_page: 10)
  end

  private

  def date_from
    params[:from].present? ? params[:from].to_date : Date.today.beginning_of_month
  end

  def date_to
    @date_to = params[:to].present? ? params[:to].to_date : Date.today.beginning_of_month
  end

  def change_status
    @student.send("#{params[:state]}!".to_sym)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/views/student_movement/_form_for_date.html.erb
<% the_months = (Date.today.prev_year.beginning_of_year..Date.today.end_of_year).select { |d| d.day == 1 } %>
<%= form_with(url: students_stipend_path, method: :get, data: {turbo_frame: "student_movement"}, html: {class: "row d-flex"}) do |form| %>
  <div class="m-2 col-md-1">
    <%= form.label :from, style: "display: block" %>
  </div>
  <div class="m-2 col-md-1">
    <%= form.select :from, the_months.map { |d| [d.strftime('%b %Y'), d] }, {:selected => params[:from]}, {:class => "form-select"} %>
  </div>
  <div class="m-2 col-md-1">
    <%= form.label :to, style: "display: block" %>
  </div>
  <div class="m-2 col-md-1">
    <%= form.select :to, the_months.map { |d| [d.strftime('%b %Y'), d] }, {:selected => params[:to]}, {:class => "form-select"} %>
  </div>
  <div class="m-2 col-md-1">
    <%= form.submit 'Search', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/student_movement/_student.html.erb
<tr id="<%= dom_id student %>">
  <td><%= student.full_name %></td>
  <% if list == "registered" %>
    <td>
      <%= link_to "Approved", update_status_path(student, state: "approved", redirect_back: "registered_students"), class: "btn btn-success" %>
      <%= link_to "Rejected", update_status_path(student, state: "rejected", redirect_back: "registered_students"), class: "btn btn-warning" %>
    </td>
  <% else %>
    <td><%= student.pending(date_to)[:amount] %></td>
    <td><%= student.pending(date_to)[:readable_month] %></td>
    <td><%= link_to "Clear Stipend", clear_pervious_path(student, date_to: date_to, redirect_back: "students_stipend", parameter: {to: params[:to], from: params[:from], page: params[:page]}), class: "btn btn-secondary" %></td>
  <% end %>
  <td><%= link_to "Show", student_path(student), class: "btn btn-info" %></td>
  <td><%= link_to "Edit", edit_student_path(student), class: "btn btn-primary" %></td>
</tr>

app/views/student_movement/registered_students.html.erb
<%= render "shared/header", show_gradient: nil %>
<h1>Students in approval list (Count: <%= @students.count %>)</h1>
<div id="students" class="m-3 height-400px">
  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Approved The Student</th>
      <th>Show</th>
      <th>Edit</th>
    </thead>
  <tbody class="table-group-divider">
    <% @students.each do |student| %>
      <%= render "student", student:, list: "registered" %>
    <% end %>
  </tbody>
  </table>
</div>
<%= will_paginate @students, list_classes: %w(pagination justify-content-center) %>

<%= link_to "New student", new_student_path, class: "btn btn-primary m-2" %>
<%= render "shared/footer" %>

app/views/student_movement/students_stipend.html.erb
<%= render "shared/header", show_gradient: nil %>
<h1>Students Stipends list (Count: <%= @all_students.length %>)</h1>
<%= render 'form_for_date' %>
<div id="students" class="height-400px">
  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Pending Stipend Amount</th>
      <th>Pending Stipend Months</th>
      <th>Give The Stipend</th>
      <th>Show</th>
      <th>Edit</th>
    </thead>
  <tbody class="table-group-divider">
    <% @students.each do |student| %>
      <%= render "student", student:, date_to: @date_to, list: "pending" %>
    <% end %>
  </tbody>
  </table>
</div>
<%= will_paginate @students, list_classes: %w(pagination justify-content-center) %>

<%= link_to "New student", new_student_path, class: "btn btn-primary m-2" %>
<%= render "shared/footer" %>