config/routes.rb
Rails.application.routes.draw do
  resources :educationals
  resources :degrees
  resources :universities
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  root :to => "main#home_page"

  devise_for :users
  resources :stipends
  resources :sponsords
  resources :categories
  resources :students do 
    collection do
      resources :registration
    end
  end

  # => Student Movement
  get '/registered_students', to: 'student_movement#registered_students', as: 'registered_students'
  get '/update_status/:id', to: 'student_movement#update_status', as: 'update_status'
  get '/students_stipend', to: 'student_movement#students_stipend', as: 'students_stipend'
  get '/clear_pervious/:id', to: 'give_stipend#clear_pervious', as: 'clear_pervious'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stipend.rb
# == Schema Information
#
# Table name: stipends
#
#  id             :integer          not null, primary key
#  amount         :integer
#  payment_method :string
#  recevied_at    :date
#  recevied_by    :string
#  stipend_in     :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  student_id     :integer
#
class Stipend < ApplicationRecord
  belongs_to :student

  def month_and_year
    [stipend_in.strftime("%B"), stipend_in.year]
  end
end

app/controllers/stipends_controller.rb
class StipendsController < ApplicationController
  before_action :set_stipend, only: %i[ show edit update destroy ]

  # GET /stipends or /stipends.json
  def index
    @stipends = Stipend.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /stipends/1 or /stipends/1.json
  def show
  end

  # GET /stipends/new
  def new
    @stipend = Stipend.new
  end

  # GET /stipends/1/edit
  def edit
  end

  # POST /stipends or /stipends.json
  def create
    @stipend = Stipend.new(stipend_params)

    respond_to do |format|
      if @stipend.save
        format.html { redirect_to stipend_url(@stipend), notice: "Stipend was successfully created." }
        format.json { render :show, status: :created, location: @stipend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stipend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stipends/1 or /stipends/1.json
  def update
    respond_to do |format|
      if @stipend.update(stipend_params)
        format.html { redirect_to stipend_url(@stipend), notice: "Stipend was successfully updated." }
        format.json { render :show, status: :ok, location: @stipend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stipend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stipends/1 or /stipends/1.json
  def destroy
    @stipend.destroy

    respond_to do |format|
      format.html { redirect_to stipends_url, notice: "Stipend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stipend
      @stipend = Stipend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stipend_params
      params.require(:stipend).permit(:student_id, :amount, :stipend_in, :recevied_at, :recevied_by, :payment_method)
    end
end

app/helpers/stipends_helper.rb
module StipendsHelper
end

app/views/stipends/_form.html.erb
<%= form_with(model: stipend, :html => {:class => "row g-3"}) do |form| %>
  <% if stipend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stipend.errors.count, "error") %> prohibited this stipend from being saved:</h2>

      <ul>
        <% stipend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating col-md-4">
    <%= form.number_field :amount, class: "form-control", placeholder: "Name",  id: "floatingInput" %>
    <%= form.label :amount, style: "display: block", for: "floatingInput" %>
  </div>

  <div class="form-floating col-md-4">
    <%= form.date_field :stipend_in, class: "form-control", placeholder: "Name",  id: "floatingInput" %>
    <%= form.label :stipend_in, style: "display: block", for: "floatingInput" %>
  </div>

  <div class="form-floating col-md-4">
    <%= form.text_field :payment_method, class: "form-control", placeholder: "Name",  id: "floatingInput" %>
    <%= form.label :payment_method, style: "display: block", for: "floatingInput" %>
  </div>

  <div class="col-md-6">
    <%= form.label :recevied_at, style: "display: block", class: "text-white" %>
    <%= form.date_field :recevied_at, class: "form-control", placeholder: "Name" %>
  </div>

  <div class="col-md-6">
    <%= form.label :recevied_by, style: "display: block", class: "text-white" %>
    <%= form.date_field :recevied_by, class: "form-control", placeholder: "Name" %>
  </div>

  <div>
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/stipends/_stipend.html.erb
<tr>
  <td><%= stipend.amount %></td>
  <td><%= stipend.stipend_in %></td>
  <td><%= stipend.recevied_at %></td>
  <td><%= stipend.recevied_by %></td>
  <td><%= stipend.payment_method %></td>
  <td><%= link_to "Show", stipend_path(stipend), class: "btn btn-info" %></td>
  <td><%= link_to "Edit", edit_stipend_path(stipend), class: "btn btn-primary" %></td>
  <td><%= button_to "Destroy", stipend, method: :delete, class: "btn btn-danger" %></td>
</tr>

app/views/stipends/_student_stipends.html.erb
<h1>Stipends</h1>
<div id="stipends" class="height-400px">
  <table class="table table-striped">
    <thead>
      <th>Amount</th>
      <th>Stipend Month</th>
      <th>Payment Method</th>
      <th>Received At</th>
      <th>Received By</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </thead>
  <tbody class="table-group-divider">
    <% stipends.each do |stipend| %>
      <%= render 'stipends/stipend', stipend: %>
    <% end %>
  </tbody>
  </table>
</div>

app/views/stipends/edit.html.erb
<%= render "shared/header", show_gradient: true %>
<div class="p-2">
  <%= link_to "Back to stipends", stipends_path, class: "btn btn-primary" %>
</div>
<div class="container p-5" style="max-width: 1000px;">
  <h1 class="text-center">Editing stipend</h1>
  <%= render "form", stipend: @stipend %>
</div>

<div class="p-2">
  <%= link_to "Show this stipend", @stipend, class: "btn btn-light" %>
</div>

app/views/stipends/index.html.erb
<p style="color: green" class="position-absolute"><%= notice %></p>
<%= render "shared/header", show_gradient: false %>
<%= render "student_stipends", stipends: @stipends %>
<%= link_to "New stipend", new_stipend_path, class: "btn btn-primary m-2" %>
<%= render "shared/footer" %>

app/views/stipends/new.html.erb
<%= render "shared/header", show_gradient: true %>
<div class="p-2">
  <%= link_to "Back to stipends", stipends_path, class: "btn btn-primary" %>
</div>
<div class="container p-5" style="max-width: 1000px;">
  <h1 class="text-center">New stipend</h1>
  <%= render "form", stipend: @stipend %>
</div>
<%= render "shared/footer" %>

app/views/stipends/show.html.erb
<p class="position-absolute" style="color: green"><%= notice %></p>
<%= render "shared/header", show_gradient: false %>
<%= link_to "Back to stipends", stipends_path, class: "btn btn-primary m-2"  %>
<div class="container row">
  <div class="d-flex col-md-4">  
    <div class="m-1 fw-bold">Amount </div>
    <div class="m-1 "><%= @stipend.amount %></div>
  </div>

  <div class="d-flex col-md-4">  
    <div class="m-1 fw-bold">Month </div>
    <div class="m-1"><%= @stipend.stipend_in %></div>
  </div>

  <div class="d-flex col-md-4">  
    <div class="m-1 fw-bold">Payment Method </div>
    <div class="m-1"><%= @stipend.payment_method %></div>
  </div>

  <div class="d-flex col-md-6">  
    <div class="m-1 fw-bold">Recevied At </div>
    <div class="m-1"><%= @stipend.recevied_at %></div>
  </div>

  <div class="d-flex col-md-6">  
    <div class="m-1 fw-bold">Recevied By </div>
    <div class="m-1"><%= @stipend.recevied_by %></div>
  </div>
  <div class="">
    <%= link_to "Edit", edit_stipend_path(@stipend), class: "btn btn-primary m-2" %>
    <%= button_to "Destroy", @stipend, method: :delete, class: "btn btn-danger m-2" %>
  </div>
</div>

<%= render "shared/footer" %>