config/routes.rb
Rails.application.routes.draw do
  resources :educationals
  resources :degrees
  resources :universities
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  root :to => "main#home_page"

  devise_for :users
  resources :stipends
  resources :sponsords
  resources :categories
  resources :students do 
    collection do
      resources :registration
    end
  end

  # => Student Movement
  get '/registered_students', to: 'student_movement#registered_students', as: 'registered_students'
  get '/update_status/:id', to: 'student_movement#update_status', as: 'update_status'
  get '/students_stipend', to: 'student_movement#students_stipend', as: 'students_stipend'
  get '/clear_pervious/:id', to: 'give_stipend#clear_pervious', as: 'clear_pervious'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :students
  def self.med
    Category.where(name: 'Medical') || Category.create(name: 'Medical')
  end

  def self.eng
    Category.where(name: 'Engineering') || Category.create(name: 'Engineering')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= link_to "Show", category_path(category), class: "btn btn-info" %></td>
  <td><%= link_to "Edit", edit_category_path(category), class: "btn btn-primary" %></td>
  <td><%= button_to "Destroy", category, method: :delete, class: "btn btn-danger" %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: category, :html => {:class => "row g-3"}) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating col-md-4">
    <%= form.text_field :name, class: "form-control", placeholder: "Name",  id: "floatingInput" %>
    <%= form.label :name, style: "display: block", for: "floatingInput" %>
  </div>

  <div>
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "shared/header", show_gradient: true %>
<div class="p-2">
  <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
</div>
<div class="container p-5" style="max-width: 1000px;">
  <h1 class="text-center">Editing category</h1>
  <%= render "form", category: @category %>
</div>

<div class="p-2">
  <%= link_to "Show this category", @category, class: "btn btn-light" %>
</div>

app/views/categories/index.html.erb
<p style="color: green" class="position-absolute"><%= notice %></p>
<%= render "shared/header", show_gradient: false %>
<h1>categories</h1>
<div id="categories">
  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </thead>
  <tbody class="table-group-divider">
    <% @categories.each do |category| %>
      <%= render category %>
    <% end %>
  </tbody>
  </table>
</div>
<%= link_to "New category", new_category_path, class: "btn btn-primary m-2" %>
<%= render "shared/footer" %>

app/views/categories/new.html.erb
<%= render "shared/header", show_gradient: true %>
<div class="p-2">
  <%= link_to "Back to categories", categories_path, class: "btn btn-primary" %>
</div>
<div class="container p-5" style="max-width: 1000px;">
  <h1 class="text-center">New category</h1>
  <%= render "form", category: @category %>
</div>
<%= render "shared/footer" %>

app/views/categories/show.html.erb
<p class="position-absolute" style="color: green"><%= notice %></p>
<%= render "shared/header", show_gradient: false %>
<%= link_to "Back to categories", categories_path, class: "btn btn-primary m-2"  %>
<div class="container row">
  <div class="d-flex col-md-4">  
    <div class="m-1 fw-bold">Name </div>
    <div class="m-1 "><%= @category.name %></div>
  </div>
  <div class="">
    <%= link_to "Edit", edit_category_path(@category), class: "btn btn-primary m-2" %>
    <%= button_to "Destroy", @category, method: :delete, class: "btn btn-danger m-2" %>
  </div>
</div>

<%= render "shared/footer" %>